<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>ProjectF.Simulation.Core</AssemblyName>
    <LangVersion>9.0</LangVersion>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup><Compile Include="../../FactorioProject/Assets/Scripts/Simulation/Core/**/*.cs" /></ItemGroup>
</Project>
